### ISSUE TITLE
MissingSchemaError prilikom pokretanja test primera iz help-a

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2020_Chat-Bot-za-Vremensku-Prognozu#6]
Kolega je pokrenuo program i pratio uputstva iz `help` komande, ali je dobio naredni error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "gui.py", line 66, in send_message
    messaging_response = messaging.receive_message_and_make_response(msg)
  File "/home/cugur/Desktop/PP_Projects_2020/2020_Chat-Bot-za-Vremensku-Prognozu-master/messaging.py", line 94, in receive_message_and_make_response
    response = determine_response(user_msg)
  File "/home/cugur/Desktop/PP_Projects_2020/2020_Chat-Bot-za-Vremensku-Prognozu-master/input_parser.py", line 94, in determine_response
    return get_by_city_name(params)
  File "/home/cugur/Desktop/PP_Projects_2020/2020_Chat-Bot-za-Vremensku-Prognozu-master/backend.py", line 50, in get_by_city_name
    obj = make_request(req)
  File "/home/cugur/Desktop/PP_Projects_2020/2020_Chat-Bot-za-Vremensku-Prognozu-master/backend.py", line 19, in make_request
    res = requests.get(req)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 506, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 449, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'weather?q=London&appid=None': No schema supplied. Perhaps you meant http://weather?q=London&appid=None?
```

Problem je izgleda loše kreiranje URL-a za request, očigledno fali protokol (schema). 

Takođe, nije rečeno, da li je potreban nekakav token za autorizaciju ili ne?

**Comment by Imafikus** [comment]
U mejlu koji sam Vam poslao kad smo zavrsili prvu verziju projekta (sto je bio tipa mart) stoji .env fajl koji je potreban za pokretanje, s obzirom da unutra stoji secret key to openweather APIja, sada cu Vam poslati ponovo isti taj fajl, i naznacicu u README-u ako vec nisam.

**Comment by ivan-ristovic** [comment]
Ah, ja sam potpuno zaboravio na taj mail, mislio sam da koristite jedan od javnih tokena. @MilanCugur će probati opet sa ovim .env fajlom.

Mada, mislim da je dobra ideja da bot, ukoliko .env fajl nije prisutan, kreira isti tako što zatraži od korisnika token. Takođe i opcije za izmenu API URL-a i tokena u .env fajlu kroz chat bi bile jako korisne. Razmislite o ovome :)

**Comment by AizenAngel** [comment]
Dodata je opcija izmene API URL-a i tokena. Hvala na sugestiji.
